DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
ID BIGINT PRIMARY KEY
, NAME VARCHAR(255)
, UNIQUE UQ_AUTHORS_1 (NAME)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
ID BIGINT PRIMARY KEY
, NAME VARCHAR(255)
, UNIQUE UQ_GENRES_1 (NAME)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
ID BIGINT PRIMARY KEY
, NAME VARCHAR(255)
, AUTHOR_ID BIGINT
, GENRE_ID BIGINT
, UNIQUE UQ_AUTHOR_BOOK_1 (AUTHOR_ID, NAME)
, CONSTRAINT FK_BOOKS_AUTHORS FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID)
, CONSTRAINT FK_BOOKS_GENRES FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID)
);